call Z:\tmp\petzold_cleanh\ch18\printcal\gox.cmd
call Z:\tmp\petzold_cleanh\ch13\popmenu\gox.cmd
call Z:\tmp\petzold_cleanh\ch13\life\gox.cmd
call Z:\tmp\petzold_cleanh\ch13\grafmenu\gox.cmd
call Z:\tmp\petzold_cleanh\ch13\convmenu\gox.cmd
call Z:\tmp\petzold_cleanh\ch13\taquin\gox.cmd
call Z:\tmp\petzold_cleanh\ch14\about2\gox.cmd
call Z:\tmp\petzold_cleanh\ch14\head\gox.cmd
call Z:\tmp\petzold_cleanh\ch14\about1\gox.cmd
call Z:\tmp\petzold_cleanh\ch14\hexcalc\gox.cmd
call Z:\tmp\petzold_cleanh\ch14\pattdlg\gox.cmd
call Z:\tmp\petzold_cleanh\ch16\buttons3\gox.cmd
call Z:\tmp\petzold_cleanh\ch16\hdrtest\gox.cmd
call Z:\tmp\petzold_cleanh\ch16\showbit\gox.cmd
call Z:\tmp\petzold_cleanh\ch17\bigjob4\gox.cmd
call Z:\tmp\petzold_cleanh\ch17\bigjob5\gox.cmd
call Z:\tmp\petzold_cleanh\ch17\bigjob1\gox.cmd
call Z:\tmp\petzold_cleanh\ch17\bigjob3\gox.cmd
call Z:\tmp\petzold_cleanh\ch17\bigjob2\gox.cmd
call Z:\tmp\petzold_cleanh\ch15\blowup\gox.cmd
call Z:\tmp\petzold_cleanh\ch15\hexcalc2\gox.cmd
call Z:\tmp\petzold_cleanh\ch12\loadbmp2\gox.cmd
call Z:\tmp\petzold_cleanh\ch12\loadbmp1\gox.cmd
call Z:\tmp\petzold_cleanh\ch12\resource\gox.cmd
call Z:\tmp\petzold_cleanh\ch12\poepoem\gox.cmd
